import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/sideBar";
import AuthCheck from "@/container/authCheck";
import Header from "@/components/header";
import LatestPosts from "@/container/clientblogcontainer/LatestPosts";
import FeaturedPosts from "@/container/clientblogcontainer/FeaturedPosts";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <div>
        <Header />
      </div>
      <div className="flex flex-row justify-center gap-6 p-6 px-4 md:px-10 lg:px-20">
      <div className="w-[60%]">{children}</div>
        <div className="w-[28%] mt-20">
          {" "}
          <FeaturedPosts />
          <LatestPosts />
        </div>
      </div>
      
      <Footer/>
    </div>
  );
}
